config/routes.rb
Rails.application.routes.draw do
  devise_for :users

	root 'home#top'
	# get '/' => 'homes#top'
	get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update, :create, :destroy]
  resources :books, only: [:index, :show, :edit, :update, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,
  	length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }

  has_many :books, dependent: :destroy

  attachment :profile_image


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?


	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	end

	def after_sign_out_path_for(resource)
		root_path
	end

	def after_sign_in_path_for(resource)
		user_path(current_user)
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!, only: [:index, :show, :edit]


	def index
		@user = current_user
		@book = Book.new
		@books = Book.all
	end

	def show
		@book = Book.new
		@book_content = Book.find(params[:id])
		@user = current_user
		@users = @book_content.user
	end

	def edit
		@user = current_user
		@book = Book.find(params[:id])
		# @book.user_id = current_user.id
		unless  @book.user_id == current_user.id
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		flash[:notice] = "Book was successfully updated"
		redirect_to book_path(@book.id)
		else
		@user = current_user
		# @book = Book.find(params[:id])
		@book.user_id = current_user.id
		render "edit"
		end
	end

	def create
		@book = Book.new(book_params)
		# @book = Book.new
		# @book.title = params[:title]
		# @book.body = params[:body]
		@book.user_id = current_user.id
		if @book.save
		flash[:notice] = "You have created book successfully "
		redirect_to book_path(@book)
		else
		@user = current_user
		@books = Book.all
		render "index"
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title, :body, :user_id)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def top
	end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!

	before_action :connecting_user, only: [:edit, :update]

	def index
		# @user = User.find(params[:id])
		@user = current_user
		@book = Book.new
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@book = Book.new
		@books = Book.where(user_id: params[:id])
		# @books = @user.books
	end

	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		flash[:notice] = "User was successfully updated"
		redirect_to user_path(@user.id)
		else
		# redirect_to edit_user_path(@user.id)
		render "edit"
		@user = current_user
		end
	end

	def create
	end

	def destroy
		flash[:notice] = "logout"
	end

	private
		def user_params
			params.require(:user).permit(:name, :introduction, :profile_image)
		end

		def connecting_user
			if current_user.id != params[:id].to_i
				redirect_to user_path(current_user)
			end
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3"></div>
		<div class="col-lg-6">
		<h2 style="padding: 10px;">Editing Book</h2>
		<%= form_for(@book) do |f| %>
		<%= render 'layouts/error_messages', model: f.object %>
			<p><strong>Title</strong></p>
			<%= f.text_field :title, class:"col-lg-12"  %>
			<p><strong>Opinion</strong></p>
			<%= f.text_area :body, class:"col-lg-12" %>

			<%= f.submit "Create Book",class: "btn btn-primary col-lg-12" %>
		<% end %>

		<span><%= link_to "show", book_path(@book) %></span>
		|
		<span><%= link_to "Back", books_path %></span>

		</div>
		<div class="col-lg-3"></div>
	</div>
</div>

app/views/books/index.html.erb
<html>
<head>
</head>
<body>
<%= render 'layouts/error_messages', model: @book %>
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<%= render 'layouts/list', user: @user, book: @book %>
		</div>
		<div class="col-md-9">
			<h2>Books</h2>
			<table>
				<tr style=" border-bottom: 2px solid #ddd">
					<td>&nbsp;</td>
					<td style="width: 300px; text-align: center;"><strong>Title</strong></td>
					<td style="width: 300px; text-align: center;"><strong>Opinion</strong></td>
				</tr>
				<% @books.each do |book| %>
				<% user = User.find(book.user_id) %>
				<tr style="border-bottom: 1px solid #ddd">
					<td><%= link_to user_path(user.id) do %>
						<%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpg', fallback: "no_image.jpg"%>
						<% end %>
						</td>
					<td style="text-align: center;"><%= link_to book.title, book_path(book.id) %>
						</td>
					<td style="text-align: center;"><%= book.body %></td>
				<% end %>
				</tr>
			</table>
		</div>
	</div>
</div>
</body>
</html>




app/views/books/show.html.erb
<html>
<head>
</head>
<body>
<% if flash[:notice] %>
	<div><%= flash[:notice] %></div>
<% end %>
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<h2>User info</h2>
		<div class="user-profile-image" style="border-bottom: 1px solid #ddd">
			<%= attachment_image_tag @users, :profile_image, format: 'jpg', fallback: "no_image.jpg", size: "100x100" %>
		</div>
		<table>
			<tbody>
				<tr style="border-bottom: 1px solid #ddd">
					<th style="padding: 8px; ">name</th>
					<th style="padding-left: 20px;"><%= @users.name %></th>
				</tr>
				<tr>
					<th style="padding: 20px 0;">introduction</th>
					<th style="padding-left: 20px;"><%= @users.introduction %></th>
				</tr>
			</tbody>
		</table>
		 <%= link_to  edit_user_path(@users) do %>
			<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" style="width: 100%; margin: 30px 0;"></span>
		<% end %>

			<h2>New Book</h2>
			<%= form_for(@book) do |f| %>
				<div><strong>Title</strong></div>
				<div><%= f.text_field :title,  class:"col-lg-12" %></div>

				<div><strong>Opinion</strong></div>
				<div><%= f.text_field :body,  class:"col-lg-12" %></div>

				<input type="submit" value="Create Book" class="btn btn-primary col-lg-12" style="margin: 10px 0;"></input>
			<% end %>
		</div>
		<div class="col-lg-9">
		<h2 style=" padding-bottom: 10px; border-bottom: 1px solid #ddd">Book detail</h2>
			<table>
				<tr>
					<td>
					<%= link_to user_path(@users) do %>
					<%= attachment_image_tag @users, :profile_image, fomat: 'jpg', fallback: "no_image.jpg", size: "100x100" %>
					<div style="text-align: center;"><%= @users.name %></div>
					<% end %>
					</td>
					<td style="width: 200px; text-align: center;">
						<%= link_to book_path(@book_content) do %>
						<%= @book_content.title %>
						<% end %>
					</td>
					<td style="width: 200px; text-align: center;"><%= @book_content.body %></td>
					<% if @book_content.user_id == current_user.id %>
					<td style="width: 50px; text-align: center; margin-top: 40px;"><%= link_to "Edit", edit_book_path(@book_content), class: "btn btn-success "%></td>
					<td style="width: 100px; text-align: center; margin: 40px 0 0 40px;"><%= link_to "Destroy", book_path(@book_content), method: :delete, class: "destroy_#{@book_content.id} btn btn-danger" %></td>
					<% end %>
				</tr>
			</table>
		</div>
	</div>
</div>
</body>
</html>

app/views/home/about.html.erb
<div class="container">
	<div class="row">
		<div style="font-size: 40px;">
			<div>welcome to <strong><div class="glyphicon glyphicon-book"></div>Bookers!</strong></div>
		</div>
	</row>
</div>

app/views/home/top.html.erb
<% if flash[:notice] %>
		<%= flash[:notice] %>
	<% end %>

<div class="container">
	<div class="row">
		<div class="col-lg-offset-4 col-log-6">
			<h2>Welcome to <strong><div class="glyphicon glyphicon-book">Boookers !!</strong>
			</h2>
			<p>In <strong>Bookers</strong>,<br>
			you can share and exchang your opinions, inpressions, and emotions<br>about varioius books!
			</p>
				<div style="width: 55%;">
				    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-info", :style=>"width: 100%;" %>
				</div>
				<div style="width: 55%;">
					<%= link_to "login", new_user_session_path, class: "btn btn-success", :style=>"width: 100%;" %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
    	<div>error!</div>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_list.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<h2>User info</h2>
				<div class="user-profile-image" style="border-bottom: 1px solid #ddd">
					<%= attachment_image_tag user, :profile_image, format: 'jpg', fallback: "no_image.jpg", size: "100x100" %>
				</div>
				<table>
					<tbody>
						<tr style="border-bottom: 1px solid #ddd">
							<th style="padding: 8px;">name</th>
							<th style="padding: 20px;"><%= user.name %></th>
						</tr>
						<tr>
							<th style="padding: 20px 0;">introduction</th>
							<th style="padding: 20px;"><%= user.introduction %></th>
						</tr>
					</tbody>
				</table>
				<%= link_to  edit_user_path(user) do %>
					<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" style="width: 100%; margin: 30px 0;"></span>
				<% end %>
				<h2>New Book</h2>
				<%= form_for(book) do |f| %>
					<div><strong>Title</strong></div>
					<div><%= f.text_field :title, class:"col-lg-12" %></div>

					<div><strong>Opinion</strong></div>
					<div><%= f.text_field :body, class:"col-lg-12" %></div>

					<%= f.submit "Create Book",class: "btn btn-primary col-lg-12" %>
				<% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track':'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track':'reload' %>
  </head>

  <body>
    <div class="container" style=" width: 100%;">
      <div class="row" style="background-color: black; height: 75px;">
        <span style="font-size: 24px; color: #ffffff; padding-left: 200px; margin-top: 5px; width: 400px;">Bookers</span>
        <div class="headmenu">
          <div style="text-align: right;">
          <ul class="navbar" style="padding-right: 50px;">
            <% if user_signed_in? %>
              <span style="padding: 0 30px;">
                <%= link_to " Home ", user_path(current_user), class: " btn btn-link glyphicon glyphicon-home", :style=>"color:#fff;" %>
              </span>
              <span style="padding: 0 30px;">
                <%= link_to " Users", users_path, class: " btn btn-link glyphicon glyphicon-user" , :style=>"color:#fff;"%>
              </span>
              <span style="padding: 0 30px;">
                <%= link_to " Books", books_path, class: "btn btn-link glyphicon glyphicon-book", :style=>"color:#fff;" %>
              </sapn>
              <span style="padding: 0 30px;">
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: "btn btn-link glyphicon glyphicon-log-out", :style=>"color:#fff;" %>
              </span>
            <% else %>
              <span style="padding: 0 30px;">
                <%= link_to " Home", root_path, class: "btn btn-link glyphicon glyphicon-home", :style=>"color:#fff;" %>
              </span>
              <span style="padding: 0 30px;">
                <%= link_to " About", home_about_path, class: "btn btn-link glyphicon glyphicon-link", :style=>"color:#fff;" %>
              </span>
              <span style="padding: 0 30px;">
                <%= link_to " Sign up", new_user_registration_path, class: "btn btn-link glyphicon glyphicon-edit", :style=>"color:#fff;" %>
              </span>
              <span style="padding: 0 30px;">
                <%= link_to " login", new_user_session_path, class: "btn btn-link glyphicon glyphicon-log-in", :style=>"color:#fff;" %>
              </span>
            <% end %>
          </ul>
          </div>
        </div>
      </div>
    </div>
    <%= yield %>
      <div style="text-align: right;">
        <footer style="padding: 20px;">CopyRight Infratop.inc</footer>
      </div>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-6">
			<h2>User info</h2>
			<%= form_for(@user) do |f| %>
			<%= render 'layouts/error_messages', model: f.object %>
				<p><strong>Name </strong><%= f.text_field :name %></p>

				<div><strong>Image</strong></div>
				<%= f.attachment_field :profile_image %>

				<p><strong>Introduction </strong><%= f.text_area :introduction %></p>

				<p><%= f.submit 'Update User'%></p>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<html>
<head>
</head>
<body>
<div class="container">
	<div class="row">
		<div class="col-md-3">
		<%= render 'layouts/list', user: @user, book: @book %>
		</div>
		<div class="col-md-9">
			<h2>Users</h2>
			<table>
				<tr style="border-bottom: 2px solid #ddd">
					<td style="text-align: center;"><strong>image<strong></td>
					<td style="width: 300px; text-align: center;"><strong>name</strong></td>
					<td style="width: 500px;">&nbsp;</td>
				</tr>
				<% @users.each do |user| %>
				<tr style="border-bottom: 1px solid #ddd">
				</style>
					<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpg', fallback: "no_image.jpg"%></td>
					<td style="text-align: center;"><%= user.name %></td>
					<td style="text-align: center;"><%= link_to "show", user_path(user.id) %></td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>
</body>
</html>


app/views/users/show.html.erb
<div class="container">
	<div class="row">
			<% if flash[:notice] %>
				<div><p><%= flash[:notice] %></p></div>
			<% end %>
		<div class="col-md-3">
			<%= render 'layouts/list', user: @user, book: @book %>
		</div>
		<div class="col-md-9">
		<h2>Books</h2>
			<table>
				<tr style=" border-bottom: 2px solid #ddd">
					<td>&nbsp;</td>
					<td style="width: 300px; text-align: center;"><strong>Title</strong></td>
					<td style="width: 300px; text-align: center;"><strong>Opinion</strong></td>
				</tr>
				<% @books.each do |book| %>
				<% user = User.find(book.user_id) %>
				<tr style=" border-bottom: 1px solid #ddd">
					<td>
						<%= link_to user_path(user.id) do %>
						<%= attachment_image_tag user, :profile_image, fomat: 'jpg', fallback: "no_image.jpg", size: "100x100" %>
						<% end %>
					</td>
					<td style="text-align: center;"><%= link_to book_path(book.id) do %>
						<%= book.title %>
						<% end %>
						</td>
					<td style="text-align: center;"><%= book.body %></td>
					<% end %>
				</tr>
			</table>
		</div>
	</div>
</div>